#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx8192M
kotlin.mpp.enableCInteropCommonization=true
kotlin.apple.xcodeCompatibility.nowarn=true
#Gradle
org.gradle.jvmargs=-Xmx8192M -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.build-cache=true
org.gradle.configuration-cache=true
org.gradle.workers.max=4
#Android
android.nonTransitiveRClass=true
android.useAndroidX=true
# Compose
compose.reload.devToolsEnabled=true
# NoCircle
no-circle.version.name=1.0.0
no-circle.version.code=1