package com.nocircle.app.theme.colors

import androidx.compose.material3.darkColorScheme
import androidx.compose.ui.graphics.Color
import com.nocircle.app.resources.AppString

data object AmberColorSchemeGroup : ColorSchemeGroup {

    override val name = AppString.AppearanceThemeAmber

    override val lightStandardContrast by lazy {
        darkColorScheme(
            primary = Color(0xFF7F5610),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFFFDDB3),
            onPrimaryContainer = Color(0xFF624000),
            secondary = Color(0xFF6F5B40),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFFADEBC),
            onSecondaryContainer = Color(0xFF56442A),
            tertiary = Color(0xFF516440),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFD4EABB),
            onTertiaryContainer = Color(0xFF3A4C2A),
            error = Color(0xFFBA1A1A),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFFDAD6),
            onErrorContainer = Color(0xFF93000A),
            background = Color(0xFFFFF8F4),
            onBackground = Color(0xFF201B13),
            surface = Color(0xFFFFF8F4),
            onSurface = Color(0xFF201B13),
            surfaceVariant = Color(0xFFF0E0CF),
            onSurfaceVariant = Color(0xFF4F4539),
            outline = Color(0xFF817567),
            outlineVariant = Color(0xFFD3C4B4),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFF362F27),
            inverseOnSurface = Color(0xFFFCEFE2),
            inversePrimary = Color(0xFFF4BD6F),
            surfaceDim = Color(0xFFE4D8CC),
            surfaceBright = Color(0xFFFFF8F4),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFFFF1E5),
            surfaceContainer = Color(0xFFF9ECDF),
            surfaceContainerHigh = Color(0xFFF3E6DA),
            surfaceContainerHighest = Color(0xFFEDE0D4),
        )
    }

    override val lightMediumContrast by lazy {
        darkColorScheme(
            primary = Color(0xFF4C3000),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFF90651F),
            onPrimaryContainer = Color(0xFFFFFFFF),
            secondary = Color(0xFF44331B),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFF7F6A4E),
            onSecondaryContainer = Color(0xFFFFFFFF),
            tertiary = Color(0xFF2A3B1B),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFF60734D),
            onTertiaryContainer = Color(0xFFFFFFFF),
            error = Color(0xFF740006),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFCF2C27),
            onErrorContainer = Color(0xFFFFFFFF),
            background = Color(0xFFFFF8F4),
            onBackground = Color(0xFF201B13),
            surface = Color(0xFFFFF8F4),
            onSurface = Color(0xFF161009),
            surfaceVariant = Color(0xFFF0E0CF),
            onSurfaceVariant = Color(0xFF3E3529),
            outline = Color(0xFF5B5144),
            outlineVariant = Color(0xFF776B5E),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFF362F27),
            inverseOnSurface = Color(0xFFFCEFE2),
            inversePrimary = Color(0xFFF4BD6F),
            surfaceDim = Color(0xFFD0C5B9),
            surfaceBright = Color(0xFFFFF8F4),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFFFF1E5),
            surfaceContainer = Color(0xFFF3E6DA),
            surfaceContainerHigh = Color(0xFFE7DBCF),
            surfaceContainerHighest = Color(0xFFDCD0C4),
        )
    }

    override val lightHighContrast by lazy {
        darkColorScheme(
            primary = Color(0xFF3F2700),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFF664200),
            onPrimaryContainer = Color(0xFFFFFFFF),
            secondary = Color(0xFF392912),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFF59462D),
            onSecondaryContainer = Color(0xFFFFFFFF),
            tertiary = Color(0xFF203111),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFF3C4E2C),
            onTertiaryContainer = Color(0xFFFFFFFF),
            error = Color(0xFF600004),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFF98000A),
            onErrorContainer = Color(0xFFFFFFFF),
            background = Color(0xFFFFF8F4),
            onBackground = Color(0xFF201B13),
            surface = Color(0xFFFFF8F4),
            onSurface = Color(0xFF000000),
            surfaceVariant = Color(0xFFF0E0CF),
            onSurfaceVariant = Color(0xFF000000),
            outline = Color(0xFF332B20),
            outlineVariant = Color(0xFF52483B),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFF362F27),
            inverseOnSurface = Color(0xFFFFFFFF),
            inversePrimary = Color(0xFFF4BD6F),
            surfaceDim = Color(0xFFC2B7AB),
            surfaceBright = Color(0xFFFFF8F4),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFFCEFE2),
            surfaceContainer = Color(0xFFEDE0D4),
            surfaceContainerHigh = Color(0xFFDFD2C6),
            surfaceContainerHighest = Color(0xFFD0C5B9),
        )
    }

    override val darkStandardContrast by lazy {
        darkColorScheme(
            primary = Color(0xFFF4BD6F),
            onPrimary = Color(0xFF452B00),
            primaryContainer = Color(0xFF624000),
            onPrimaryContainer = Color(0xFFFFDDB3),
            secondary = Color(0xFFDDC2A1),
            onSecondary = Color(0xFF3E2D16),
            secondaryContainer = Color(0xFF56442A),
            onSecondaryContainer = Color(0xFFFADEBC),
            tertiary = Color(0xFFB8CEA1),
            onTertiary = Color(0xFF243515),
            tertiaryContainer = Color(0xFF3A4C2A),
            onTertiaryContainer = Color(0xFFD4EABB),
            error = Color(0xFFFFB4AB),
            onError = Color(0xFF690005),
            errorContainer = Color(0xFF93000A),
            onErrorContainer = Color(0xFFFFDAD6),
            background = Color(0xFF18120B),
            onBackground = Color(0xFFEDE0D4),
            surface = Color(0xFF18120B),
            onSurface = Color(0xFFEDE0D4),
            surfaceVariant = Color(0xFF4F4539),
            onSurfaceVariant = Color(0xFFD3C4B4),
            outline = Color(0xFF9C8F80),
            outlineVariant = Color(0xFF4F4539),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFFEDE0D4),
            inverseOnSurface = Color(0xFF362F27),
            inversePrimary = Color(0xFF7F5610),
            surfaceDim = Color(0xFF18120B),
            surfaceBright = Color(0xFF3F3830),
            surfaceContainerLowest = Color(0xFF120D07),
            surfaceContainerLow = Color(0xFF201B13),
            surfaceContainer = Color(0xFF251F17),
            surfaceContainerHigh = Color(0xFF2F2921),
            surfaceContainerHighest = Color(0xFF3B342B),
        )
    }

    override val darkMediumContrast by lazy {
        darkColorScheme(
            primary = Color(0xFFFFD6A0),
            onPrimary = Color(0xFF362100),
            primaryContainer = Color(0xFFB8883F),
            onPrimaryContainer = Color(0xFF000000),
            secondary = Color(0xFFF4D8B6),
            onSecondary = Color(0xFF32230C),
            secondaryContainer = Color(0xFFA58D6F),
            onSecondaryContainer = Color(0xFF000000),
            tertiary = Color(0xFFCEE4B6),
            onTertiary = Color(0xFF1A2A0B),
            tertiaryContainer = Color(0xFF83976E),
            onTertiaryContainer = Color(0xFF000000),
            error = Color(0xFFFFD2CC),
            onError = Color(0xFF540003),
            errorContainer = Color(0xFFFF5449),
            onErrorContainer = Color(0xFF000000),
            background = Color(0xFF18120B),
            onBackground = Color(0xFFEDE0D4),
            surface = Color(0xFF18120B),
            onSurface = Color(0xFFFFFFFF),
            surfaceVariant = Color(0xFF4F4539),
            onSurfaceVariant = Color(0xFFE9DAC9),
            outline = Color(0xFFBEB0A0),
            outlineVariant = Color(0xFF9B8E80),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFFEDE0D4),
            inverseOnSurface = Color(0xFF2F2921),
            inversePrimary = Color(0xFF644100),
            surfaceDim = Color(0xFF18120B),
            surfaceBright = Color(0xFF4B433A),
            surfaceContainerLowest = Color(0xFF0B0703),
            surfaceContainerLow = Color(0xFF231D15),
            surfaceContainer = Color(0xFF2D271F),
            surfaceContainerHigh = Color(0xFF383129),
            surfaceContainerHighest = Color(0xFF443C34),
        )
    }

    override val darkHighContrast by lazy {
        darkColorScheme(
            primary = Color(0xFFFFEDDA),
            onPrimary = Color(0xFF000000),
            primaryContainer = Color(0xFFF0B96B),
            onPrimaryContainer = Color(0xFF130900),
            secondary = Color(0xFFFFEDDA),
            onSecondary = Color(0xFF000000),
            secondaryContainer = Color(0xFFD9BE9E),
            onSecondaryContainer = Color(0xFF130900),
            tertiary = Color(0xFFE1F7C8),
            onTertiary = Color(0xFF000000),
            tertiaryContainer = Color(0xFFB4CA9D),
            onTertiaryContainer = Color(0xFF040E00),
            error = Color(0xFFFFECE9),
            onError = Color(0xFF000000),
            errorContainer = Color(0xFFFFAEA4),
            onErrorContainer = Color(0xFF220001),
            background = Color(0xFF18120B),
            onBackground = Color(0xFFEDE0D4),
            surface = Color(0xFF18120B),
            onSurface = Color(0xFFFFFFFF),
            surfaceVariant = Color(0xFF4F4539),
            onSurfaceVariant = Color(0xFFFFFFFF),
            outline = Color(0xFFFEEDDD),
            outlineVariant = Color(0xFFCFC0B0),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFFEDE0D4),
            inverseOnSurface = Color(0xFF000000),
            inversePrimary = Color(0xFF644100),
            surfaceDim = Color(0xFF18120B),
            surfaceBright = Color(0xFF574F46),
            surfaceContainerLowest = Color(0xFF000000),
            surfaceContainerLow = Color(0xFF251F17),
            surfaceContainer = Color(0xFF362F27),
            surfaceContainerHigh = Color(0xFF423A32),
            surfaceContainerHighest = Color(0xFF4D453D),
        )
    }
}