[versions]
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"

# Common
kotlin = "2.2.20"
ksp = "2.2.20-2.0.3"
ktor = "3.3.0"
ktorfitx = "3.3.0-3.1.1"
kotlinx-datetime = "0.7.1"
logback-classic = "1.5.18"

# Kotlin Multiplatform
agp = "8.11.2"
compose-multiplatform = "1.10.0-alpha01"
material3 = "1.9.0-beta04"
navigation3 = "1.0.0-alpha01"
navigation-compose = "2.9.0-rc01"
androidx-activity-compose = "1.11.0"
hot-reload = "1.0.0-beta06"
kotlinx-coroutines-swing = "1.10.2"
room = "2.8.0"
sqlite = "2.6.0"
koin = "4.1.1"
coil3 = "3.3.0"

# Ktor Server
exposed = "1.0.0-rc-1"
r2dbc-postgresql = "1.0.7.RELEASE"
redisson = "3.51.0"
hutool = "5.8.40"
#noinspection NewerVersionAvailable
tinypinyin = "2.0.3.RELEASE"

[libraries]

# Common
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }

# Kotlin Multiplatform
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines-swing" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity-compose" }
androidx-navigation-compose = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }
navigation3-ui = { group = "org.jetbrains.androidx.navigation3", name = "navigation3-ui", version.ref = "navigation3" }
material3-window-size-clazz = { group = "org.jetbrains.compose.material3", name = "material3-window-size-class", version.ref = "material3" }
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil3" }
coil-network-ktor3 = { group = "io.coil-kt.coil3", name = "coil-network-ktor3", version.ref = "coil3" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-paging = { group = "androidx.room", name = "room-paging", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
sqlite-bundled = { group = "androidx.sqlite", name = "sqlite-bundled", version.ref = "sqlite" }
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-compose-viewmodel = { group = "io.insert-koin", name = "koin-compose-viewmodel", version.ref = "koin" }
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-darwin = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }

# Ktor Server
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
ktor-server-core = { group = "io.ktor", name = "ktor-server-core-jvm", version.ref = "ktor" }
ktor-server-websockets = { group = "io.ktor", name = "ktor-server-websockets-jvm", version.ref = "ktor" }
ktor-server-auth = { group = "io.ktor", name = "ktor-server-auth-jvm", version.ref = "ktor" }
ktor-server-auth-jwt = { group = "io.ktor", name = "ktor-server-auth-jwt-jvm", version.ref = "ktor" }
ktor-server-content-negotiation = { group = "io.ktor", name = "ktor-server-content-negotiation-jvm", version.ref = "ktor" }
ktor-server-netty = { group = "io.ktor", name = "ktor-server-netty-jvm", version.ref = "ktor" }
ktor-server-config-yaml = { group = "io.ktor", name = "ktor-server-config-yaml-jvm", version.ref = "ktor" }
ktor-server-status-pages = { group = "io.ktor", name = "ktor-server-status-pages-jvm", version.ref = "ktor" }
exposed-core = { group = "org.jetbrains.exposed", name = "exposed-core", version.ref = "exposed" }
exposed-r2dbc = { group = "org.jetbrains.exposed", name = "exposed-r2dbc", version.ref = "exposed" }
exposed-kotlin-datetime = { group = "org.jetbrains.exposed", name = "exposed-kotlin-datetime", version.ref = "exposed" }
r2dbc-postgresql = { group = "org.postgresql", name = "r2dbc-postgresql", version.ref = "r2dbc-postgresql" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback-classic" }
hutool-crypto = { group = "cn.hutool", name = "hutool-crypto", version.ref = "hutool" }
hutool-extra = { group = "cn.hutool", name = "hutool-extra", version.ref = "hutool" }
redisson = { group = "org.redisson", name = "redisson", version.ref = "redisson" }
tinypinyin = { group = "io.github.biezhi", name = "TinyPinyin", version.ref = "tinypinyin" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "room" }
hot-reload = { id = "org.jetbrains.compose.hot-reload", version.ref = "hot-reload" }
ktorfitx-multiplatform = { id = "cn.ktorfitx.multiplatform", version.ref = "ktorfitx" }
ktorfitx-server = { id = "cn.ktorfitx.server", version.ref = "ktorfitx" }

[bundles]
multiplatform-app = [
    'kotlin-reflect',
    'androidx-navigation-compose',
    'navigation3-ui',
    'material3-window-size-clazz',
    'koin-core',
    'koin-compose-viewmodel',
    'ktor-client-core',
    'ktor-client-content-negotiation',
    'ktor-serialization-kotlinx-json',
    'coil-compose',
    'coil-network-ktor3',
]

multiplatform-app-desktop = [
    'kotlinx-coroutines-swing',
    'ktor-client-okhttp',
    'logback-classic'
]

multiplatform-app-android = [
    'androidx-activity-compose',
    'ktor-client-okhttp'
]

multiplatform-app-ios = [
    'ktor-client-darwin'
]

multiplatform-compose = [
    'kotlin-reflect',
    'koin-compose-viewmodel',
    'coil-compose',
    'coil-network-ktor3',
    'material3-window-size-clazz',
    'androidx-navigation-compose',
    'navigation3-ui',
    'ktor-serialization-kotlinx-json'
]

multiplatform-compose-android = [
    'androidx-activity-compose'
]

multiplatform-compose-desktop = [
    'kotlinx-coroutines-swing'
]

multiplatform-common = [
    'kotlin-reflect',
    'room-runtime',
    'room-paging',
    'sqlite-bundled',
    'ktor-serialization-kotlinx-json',
    'kotlinx-datetime'
]

server-app = [
    'kotlin-reflect',
    'ktor-server-core',
    'ktor-server-websockets',
    'ktor-server-auth',
    'ktor-server-auth-jwt',
    'ktor-server-content-negotiation',
    'ktor-server-netty',
    'ktor-server-config-yaml',
    'ktor-server-status-pages',
    'ktor-serialization-kotlinx-json',
    'exposed-core',
    'exposed-r2dbc',
    'exposed-kotlin-datetime',
    'r2dbc-postgresql',
    'logback-classic',
    'hutool-crypto',
    'redisson'
]

server-common = [
    'kotlin-reflect',
    'ktor-server-core',
    'ktor-server-websockets',
    'ktor-server-auth',
    'ktor-server-auth-jwt',
    'ktor-server-config-yaml',
    'ktor-serialization-kotlinx-json',
    'exposed-core',
    'exposed-r2dbc',
    'exposed-kotlin-datetime',
    'hutool-extra',
    'tinypinyin'
]

shared = [
    'ktor-serialization-kotlinx-json'
]