Login : 登录
LoginPleaseInputUsername : 请输入用户名
LoginPleaseInputPassword : 请输入密码
LoginToRegister : 去注册
LoginSuccess : 登录成功

Register : 注册
RegisterPleaseInputUsername : 请输入用户名
RegisterPleaseInputPassword : 请输入密码
RegisterPleaseConfirmPassword : 请确认密码
RegisterBackToLogin : 返回登录
RegisterUsernameLengthAtLeast8 : 用户名至少是8位
RegisterPasswordLengthAtLeast8 : 密码至少是8位
RegisterPasswordsAreInconsistentTwice : 两次密码不一致
RegisterSuccess : 注册成功，请前往登录

MainHome : 主页
MainFriends : 好友
MainGroups : 群组
MainPerson : 我的
MainPrevious : 上一页
MainCollapse : 收起
MainExpand : 展开

PersonAccount : 账号：{}
PersonSettingsSubtitle : 外观，退出登录

Settings : 设置
SettingsAppearanceSubtitle : 对比度，深浅色模式，主题色
SettingsLogout : 退出登录
SettingsLogoutTitle : 您确定要退出账号吗？
SettingsLogoutContent : 退出当前账号后，您需要重新登录
SettingsSwitchLanguage : 切换语言

Appearance : 外观
AppearanceInUse : 使用中
AppearanceSingleLine : 单行显示
AppearanceMultiLine : 全部显示 ({})
AppearanceContrast : 对比度
AppearanceContrastStandard : 标准对比度
AppearanceContrastMedium : 中对比度
AppearanceContrastHigh : 高对比度
AppearanceContrastPreview : 对比度预览
AppearanceThemeMode : 深浅色模式
AppearanceThemeModeLight : 浅色主题
AppearanceThemeModeDark : 深色主题
AppearanceThemeModeSystem : 跟随系统
AppearanceThemeModePreview : 深浅色预览
AppearanceTheme : 主题色
AppearanceThemeRed : 山霞红
AppearanceThemePurple : 云暮紫
AppearanceThemeModena : 岭夜紫
AppearanceThemeBlue : 天远蓝
AppearanceThemeLightBlue : 晨岚蓝
AppearanceThemeCyan : 岸水青
AppearanceThemeTurquoise : 湖翠青
AppearanceThemeGreen : 径幽绿
AppearanceThemeLightGreen : 野新绿
AppearanceThemeStoneGray : 崖烟灰
AppearanceThemeYellow : 原暖黄
AppearanceThemeAmber : 林暮黄
AppearanceThemePreview : 主题色预览