package com.nocircle.app.resources

import com.nocircle.common.resources.NoString

enum class AppString : NoString {
    Login,
    LoginPleaseInputUsername,
    LoginPleaseInputPassword,
    LoginToRegister,
    LoginSuccess,
    Register,
    RegisterPleaseInputUsername,
    RegisterPleaseInputPassword,
    RegisterPleaseConfirmPassword,
    RegisterBackToLogin,
    RegisterUsernameLengthAtLeast8,
    RegisterPasswordLengthAtLeast8,
    RegisterPasswordsAreInconsistentTwice,
    RegisterSuccess,
    MainHome,
    MainFriends,
    MainGroups,
    MainPerson,
    MainPrevious,
    MainCollapse,
    MainExpand,
    PersonAccount,
    PersonSettingsSubtitle,
    PersonLastLoginTime,
    Label,
    LabelTitle,
    LabelPleaseInputLabelName,
    LabelRed,
    LabelGreen,
    LabelBlue,
    LabelPreview,
    LabelPreinstall,
    LabelDelete,
    LabelUpdate,
    LabelCancel,
    LabelAdd,
    LabelMustNotEmpty,
    Settings,
    SettingsAppearanceSubtitle,
    SettingsLogout,
    SettingsLogoutTitle,
    SettingsLogoutContent,
    SettingsSwitchLanguage,
    Appearance,
    AppearanceSingleLine,
    AppearanceMultiLine,
    AppearanceContrast,
    AppearanceContrastStandard,
    AppearanceContrastMedium,
    AppearanceContrastHigh,
    AppearanceContrastPreview,
    AppearanceThemeMode,
    AppearanceThemeModeLight,
    AppearanceThemeModeDark,
    AppearanceThemeModeSystem,
    AppearanceThemeModePreview,
    AppearanceTheme,
    AppearanceThemeRed,
    AppearanceThemePurple,
    AppearanceThemeModena,
    AppearanceThemeBlue,
    AppearanceThemeLightBlue,
    AppearanceThemeCyan,
    AppearanceThemeTurquoise,
    AppearanceThemeGreen,
    AppearanceThemeLightGreen,
    AppearanceThemeStoneGray,
    AppearanceThemeYellow,
    AppearanceThemeAmber,
    AppearanceThemePreview;

    override val packageName = "com.nocircle.app"
}